version: "3.7"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: methlab_local_django
    container_name: methlab_django
    depends_on:
      - postgres
      - redis
    volumes:
      - ./samples:/wip
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: methlab_local_postgres
    container_name: methlab_postgres
    shm_size: '0.5gb'
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    
  
      
  redis:
    image: redis:6.0
    container_name: methlab_redis

  celeryworker:
    <<: *django
    image: methlab_local_celeryworker
    container_name: methlab_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    environment:
      HTTPS_PROXY: ${https_proxy}
      HTTP_PROXY: ${http_proxy}
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: methlab_local_celerybeat
    container_name: methlab_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    image: mher/flower:0.9.5
    container_name: methlab_flower
    ports:
      - "5555:5555"
    command: ["--app config.celery_app", "--broker=redis://redis:6379/0"]
    restart: unless-stopped

  nginx:
    build: ./nginx/.
    ports:
      - "8080:8080"
    depends_on:
      - django