version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: methlab_local_django
    container_name: methlab_django
    depends_on:
      - postgres
      - redis
    volumes:
      - ./samples:/tmp
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: methlab_production_postgres
    container_name: methlab_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
      
  redis:
    image: redis:5.0
    container_name: methlab_redis

  celeryworker:
    <<: *django
    image: methlab_local_celeryworker
    container_name: methlab_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: methlab_local_celerybeat
    container_name: methlab_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: methlab_local_flower
    container_name: methlab_flower
    ports:
      - "5555:5555"
    command: /start-flower
