# Generated by Django 3.1 on 2020-08-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='spf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
