# Generated by Django 3.0.5 on 2020-06-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ioc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.CharField(max_length=500)),
                ('domain', models.CharField(max_length=200)),
            ],
        ),
    ]
