# Generated by Django 3.0.5 on 2020-06-18 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_ioc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='mail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Mail'),
            preserve_default=False,
        ),
    ]
