# Generated by Django 3.1 on 2020-08-13 13:22

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_mail_spf"),
    ]

    operations = [
        TrigramExtension(),
    ]
