# Generated by Django 3.1 on 2020-08-13 14:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200813_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='color',
            field=colorfield.fields.ColorField(default='#30357B', max_length=18),
        ),
    ]
