# Generated by Django 3.0.5 on 2020-06-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_ioc_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
