# Generated by Django 3.1.1 on 2020-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200813_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='body',
            new_name='text_html',
        ),
        migrations.AddField(
            model_name='mail',
            name='text_not_managed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='text_plain',
            field=models.TextField(blank=True, null=True),
        ),
    ]
