# Generated by Django 3.0.5 on 2020-06-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200618_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.FilePathField(blank=True, max_length=500, null=True),
        ),
    ]
