# Generated by Django 3.0.5 on 2020-06-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200618_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='filepath',
            field=models.FilePathField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
