# Generated by Django 3.1.2 on 2020-12-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20201015_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalinfo',
            name='misp_api',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='internalinfo',
            name='misp_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='whitelist',
            constraint=models.UniqueConstraint(fields=('value', 'type'), name='duplicated_wl'),
        ),
    ]
