# Generated by Django 3.0.5 on 2020-06-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200618_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='filepath',
            field=models.FilePathField(default='/tmp/', max_length=500, path='/tmp/'),
            preserve_default=False,
        ),
    ]
