# Generated by Django 3.0.5 on 2020-06-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200618_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='filepath',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
