# Generated by Django 3.0.5 on 2020-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200618_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ioc',
            name='mail',
        ),
        migrations.AddField(
            model_name='ioc',
            name='whitelisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mail',
            name='iocs',
            field=models.ManyToManyField(related_name='iocs', to='shop.Ioc'),
        ),
    ]
