# Generated by Django 3.0.5 on 2020-06-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200619_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='addresses_bcc',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='addresses_cc',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='addresses_from',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='addresses_to',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='reply_to',
        ),
        migrations.CreateModel(
            name='Mail_Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiels', models.CharField(choices=[('from', 'from'), ('to', 'to'), ('bcc', 'bcc'), ('cc', 'cc'), ('reply_to', 'reply_to')], max_length=10)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Address')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Mail')),
            ],
        ),
        migrations.AddField(
            model_name='mail',
            name='addresses',
            field=models.ManyToManyField(related_name='addresses', through='shop.Mail_Addresses', to='shop.Address'),
        ),
    ]
