# Generated by Django 3.0.5 on 2020-06-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200619_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail_addresses',
            old_name='fiels',
            new_name='field',
        ),
    ]
