# Generated by Django 3.0.5 on 2020-06-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_auto_20200619_1813"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalinfo",
            name="misp_api",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="internalinfo",
            name="misp_url",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
