# Generated by Django 3.0.5 on 2020-06-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_analyzer_supported_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzer',
            name='priority',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
    ]
