# Generated by Django 3.0.5 on 2020-06-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_auto_20200622_1821"),
    ]

    operations = [
        migrations.CreateModel(
            name="Whitelist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "address"),
                            (2, "domain"),
                            (3, "ip"),
                            (4, "md5"),
                            (5, "sha256"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="address", name="whitelist",),
        migrations.RemoveField(model_name="ioc", name="whitelisted",),
        migrations.AddField(
            model_name="report",
            name="analyzer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.Analyzer",
            ),
            preserve_default=False,
        ),
    ]
