# Generated by Django 3.0.5 on 2020-06-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20200624_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='type',
            field=models.CharField(choices=[('address', 'address'), ('domain', 'domain'), ('ip', 'ip'), ('md5', 'md5'), ('sha256', 'sha256')], max_length=8),
        ),
    ]
