# Generated by Django 3.0.7 on 2020-06-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20200624_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='body_plain',
        ),
    ]
