# Generated by Django 3.0.7 on 2020-06-26 11:57

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_mail_body_plain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalinfo',
            name='honeypot_emails',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
