# Generated by Django 3.0.5 on 2020-06-30 12:49

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20200626_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='text_not_managed',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='text_plain',
        ),
        migrations.AddField(
            model_name='mail',
            name='attachments',
            field=models.ManyToManyField(related_name='attachments', to='shop.Attachment'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
    ]
