# Generated by Django 3.0.5 on 2020-06-30 13:43

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_attachment_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='mail',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
