# Generated by Django 3.0.5 on 2020-06-30 14:10

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20200630_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='charset',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_transfer_encoding',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mail_content_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='defects_categories',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='mail',
            name='message_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mail',
            name='to_domains',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
    ]
