# Generated by Django 3.0.5 on 2020-06-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20200630_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='message_id',
            field=models.CharField(max_length=1000),
        ),
    ]
