# Generated by Django 3.0.7 on 2020-07-02 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20200630_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='defects',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='defects_categories',
        ),
    ]
