# Generated by Django 3.0.7 on 2020-07-02 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_auto_20200702_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='level_worst',
        ),
    ]
