# Generated by Django 3.0.7 on 2020-07-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_remove_report_level_worst'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
