# Generated by Django 3.0.7 on 2020-07-06 13:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_report_success'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mail',
            managers=[
                ('external_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
