# Generated by Django 3.0.7 on 2020-07-07 13:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20200706_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioc',
            name='whois',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='geo_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
