# Generated by Django 3.0.7 on 2020-07-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20200709_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='geo_info',
            new_name='geom',
        ),
    ]
