# Generated by Django 3.0.7 on 2020-07-14 13:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_auto_20200709_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='mail',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='shop_mail_search__5e794b_gin'),
        ),
    ]
