# Generated by Django 3.0.7 on 2020-07-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20200714_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mx_check',
            field=models.BooleanField(default=False),
        ),
    ]
