# Generated by Django 3.0.7 on 2020-07-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_address_mx_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mx_check',
            field=models.TextField(blank=True, null=True),
        ),
    ]
