# Generated by Django 3.0.7 on 2020-07-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20200720_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, blank=True, null=True),
        ),
    ]
