# Generated by Django 3.0.7 on 2020-07-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_analyzer_onpremise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='path',
            new_name='attachments_path',
        ),
        migrations.AddField(
            model_name='mail',
            name='eml_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
