# Generated by Django 3.0.7 on 2020-07-22 10:35

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0046_auto_20200721_1216"),
    ]

    operations = [
        TrigramExtension(),
    ]
