# Generated by Django 3.1 on 2020-08-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_mail_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='official_response',
            field=models.PositiveIntegerField(choices=[(0, 'Unknown'), (1, 'SPAM'), (2, 'HAM'), (3, 'Phishing'), (4, 'Social Engineering'), (5, 'Reconnaissance'), (6, 'BlackMail'), (7, 'CEO SCAM'), (10, 'licit')], default=0),
        ),
        migrations.AddField(
            model_name='mail',
            name='progress',
            field=models.PositiveIntegerField(choices=[(0, 'new'), (1, 'processing'), (2, 'done')], default=0),
        ),
        migrations.AddField(
            model_name='mail',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mail',
            name='suggested_response',
            field=models.PositiveIntegerField(choices=[(0, 'Unknown'), (1, 'SPAM'), (2, 'HAM'), (3, 'Phishing'), (4, 'Social Engineering'), (5, 'Reconnaissance'), (6, 'BlackMail'), (7, 'CEO SCAM'), (10, 'licit')], default=0),
        ),
    ]
