# Generated by Django 3.1 on 2020-08-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0049_auto_20200807_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioc',
            name='whois',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='received',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
