# Generated by Django 3.1 on 2020-08-07 09:54

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_auto_20200807_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='mail',
            name='flags',
        ),
        migrations.AddField(
            model_name='flag',
            name='slug',
            field=models.SlugField(default='smile', max_length=100, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='flag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='CustomTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.flag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='mail',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='shop.CustomTags', to='shop.Flag', verbose_name='Tags'),
        ),
    ]
