# Generated by Django 3.1 on 2020-08-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_auto_20200807_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtags',
            name='content_object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.mail'),
            preserve_default=False,
        ),
    ]
