# Generated by Django 3.1 on 2020-08-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_customtags_content_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtags',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Mail_Flag',
        ),
    ]
