# Generated by Django 3.1 on 2020-08-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='dmark',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customtags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_customtagss', to='shop.flag'),
        ),
    ]
