# Generated by Django 3.1 on 2020-08-07 13:48

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_auto_20200807_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mail')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_customtags', to='shop.flag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomTags',
        ),
        migrations.AlterField(
            model_name='mail',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='shop.CustomTag', to='shop.Flag', verbose_name='Tags'),
        ),
    ]
