# Generated by Django 3.1 on 2020-08-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_auto_20200807_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='slug_subject',
            field=models.SlugField(default=models.CharField(max_length=500), max_length=500),
        ),
    ]
